interface FieldSchema {
  name: string;
  type: string;
  isDerived?: boolean;
  target?: string;
  precision?: string;
}

interface ModelSchema {
  name: string;
  label: string;
  collection: string;
  securityDomains?: string[];
  fields: FieldSchema[];
}

const HEADER = '// AUTO-GENERATED by `everywhere bind` -- do not edit manually.\n';

// Native Workday reference types — not app-owned BOs, so MULTI_INSTANCE stays string[]
const NATIVE_TARGETS = new Set(['WORKER', 'LOCATION', 'ORGANIZATION']);

function fieldTypeToTS(field: FieldSchema, knownModelNames?: Set<string>): string {
  switch (field.type) {
    case 'TEXT':
    case 'DATE':
      return 'string';
    case 'SINGLE_INSTANCE':
      return 'string';
    case 'BOOLEAN':
      return 'boolean';
    case 'MULTI_INSTANCE':
      if (field.target && !NATIVE_TARGETS.has(field.target) && knownModelNames?.has(field.target)) {
        return `${field.target}[]`;
      }
      return 'string[]';
    case 'CURRENCY':
      return 'CurrencyValue';
    case 'DECIMAL':
    case 'NUMERIC':
      return 'number';
    default:
      return 'unknown';
  }
}

function pluralize(name: string): string {
  if (name.endsWith('s')) return name + 'es';
  if (name.endsWith('y') && !/[aeiou]y$/i.test(name)) return name.slice(0, -1) + 'ies';
  return name + 's';
}

export function generateModels(schemas: ModelSchema[]): string {
  const knownModelNames = new Set(schemas.map((s) => s.name));
  const needsCurrencyValue = schemas.some((s) => s.fields.some((f) => f.type === 'CURRENCY'));
  const lines = [HEADER];

  if (needsCurrencyValue) {
    lines.push("import type { CurrencyValue } from '@workday/everywhere';");
    lines.push('');
  }

  for (const schema of schemas) {
    lines.push(`export interface ${schema.name} {`);
    lines.push('  id: string;');
    for (const field of schema.fields) {
      const tsType = fieldTypeToTS(field, knownModelNames);
      const readonly = field.isDerived ? 'readonly ' : '';
      lines.push(`  ${readonly}${field.name}: ${tsType};`);
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

export function generateSchema(schemas: ModelSchema[]): string {
  const lines = [HEADER];

  lines.push("import type { ModelSchema } from '@workday/everywhere';");
  lines.push('');
  lines.push('export const schemas: Record<string, ModelSchema> = {');

  for (const schema of schemas) {
    lines.push(`  ${schema.name}: {`);
    lines.push(`    name: '${schema.name}',`);
    lines.push(`    label: '${schema.label}',`);
    lines.push(`    collection: '${schema.collection}',`);
    lines.push(`    securityDomains: ${JSON.stringify(schema.securityDomains ?? [])},`);
    lines.push('    fields: [');
    for (const field of schema.fields) {
      const parts = [`name: '${field.name}'`, `type: '${field.type}'`];
      if (field.isDerived) parts.push(`isDerived: true`);
      if (field.target) parts.push(`target: '${field.target}'`);
      if (field.precision) parts.push(`precision: '${field.precision}'`);
      lines.push(`      { ${parts.join(', ')} },`);
    }
    lines.push('    ],');
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

export function generateModelHooks(schema: ModelSchema): string {
  const { name } = schema;
  const plural = pluralize(name);
  const lines = [HEADER];

  lines.push("import { useQuery, useMutation } from '@workday/everywhere';");
  lines.push(`import type { QueryResult } from '@workday/everywhere';`);
  lines.push(`import type { ${name} } from './models.js';`);
  lines.push('');
  lines.push(`export function use${plural}(options?: Parameters<typeof useQuery>[1]) {`);
  lines.push(
    `  return useQuery<${name}>('${name}', options) as QueryResult<${name}> & { data: ${name}[] | null };`
  );
  lines.push('}');
  lines.push('');
  lines.push(`export function use${name}(id: string) {`);
  lines.push(
    `  return useQuery<${name}>('${name}', { id }) as QueryResult<${name}> & { data: ${name} | null };`
  );
  lines.push('}');
  lines.push('');
  lines.push(`export function use${name}Mutation() {`);
  lines.push(`  return useMutation<${name}>('${name}');`);
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

export function generateIndex(schemas: ModelSchema[]): string {
  const lines = [HEADER];

  lines.push("export * from './models.js';");
  lines.push("export * from './schema.js';");
  for (const schema of schemas) {
    lines.push(`export * from './${schema.name}.js';`);
  }
  lines.push('');

  return lines.join('\n');
}
