// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import { useQuery, useMutation } from '@workday/everywhere';
import type { QueryResult } from '@workday/everywhere';
import type { CharityFiles } from './models.js';

export function useCharityFileses(options?: Parameters<typeof useQuery>[1]) {
  return useQuery<CharityFiles>('CharityFiles', options) as QueryResult<CharityFiles> & {
    data: CharityFiles[] | null;
  };
}

export function useCharityFiles(id: string) {
  return useQuery<CharityFiles>('CharityFiles', { id }) as QueryResult<CharityFiles> & {
    data: CharityFiles | null;
  };
}

export function useCharityFilesMutation() {
  return useMutation<CharityFiles>('CharityFiles');
}
