// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import { useQuery, useMutation } from '@workday/everywhere';
import type { QueryResult } from '@workday/everywhere';
import type { Charity } from './models.js';

export function useCharities(options?: Parameters<typeof useQuery>[1]) {
  return useQuery<Charity>('Charity', options) as QueryResult<Charity> & { data: Charity[] | null };
}

export function useCharity(id: string) {
  return useQuery<Charity>('Charity', { id }) as QueryResult<Charity> & { data: Charity | null };
}

export function useCharityMutation() {
  return useMutation<Charity>('Charity');
}
