// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import type { ModelSchema } from '@workday/everywhere';

export const schemas: Record<string, ModelSchema> = {
  Charity: {
    name: 'Charity',
    label: 'Charity',
    collection: 'charities',
    securityDomains: ['ManageCharities'],
    fields: [
      { name: 'name', type: 'TEXT' },
      { name: 'description', type: 'TEXT' },
      { name: 'matchDonations', type: 'BOOLEAN' },
      { name: 'relationshipManager', type: 'SINGLE_INSTANCE', target: 'WORKER' },
      { name: 'logo', type: 'SINGLE_INSTANCE', target: 'CharityLogo' },
      { name: 'createdBy', type: 'SINGLE_INSTANCE', target: 'WORKER' },
      { name: 'logoUploadedBefore2022', type: 'BOOLEAN', isDerived: true },
      { name: 'logoLabel', type: 'TEXT', isDerived: true },
      { name: 'workdayMatched', type: 'BOOLEAN', isDerived: true },
    ],
  },
  CharityFiles: {
    name: 'CharityFiles',
    label: 'Charity Files',
    collection: 'charityFiles',
    securityDomains: ['ManageCharities'],
    fields: [
      { name: 'uploadedBy', type: 'SINGLE_INSTANCE', target: 'WORKER' },
      { name: 'uploadedDate', type: 'DATE', precision: 'DAY' },
      { name: 'charity', type: 'SINGLE_INSTANCE', target: 'Charity' },
    ],
  },
  CharityLogo: {
    name: 'CharityLogo',
    label: 'Charity Logo',
    collection: 'charityLogos',
    securityDomains: ['ManageCharities'],
    fields: [
      { name: 'uploadedBy', type: 'SINGLE_INSTANCE', target: 'WORKER' },
      { name: 'uploadedDate', type: 'DATE', precision: 'DAY' },
    ],
  },
};
