// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import { useQuery, useMutation } from '@workday/everywhere';
import type { QueryResult } from '@workday/everywhere';
import type { CharityLogo } from './models.js';

export function useCharityLogos(options?: Parameters<typeof useQuery>[1]) {
  return useQuery<CharityLogo>('CharityLogo', options) as QueryResult<CharityLogo> & {
    data: CharityLogo[] | null;
  };
}

export function useCharityLogo(id: string) {
  return useQuery<CharityLogo>('CharityLogo', { id }) as QueryResult<CharityLogo> & {
    data: CharityLogo | null;
  };
}

export function useCharityLogoMutation() {
  return useMutation<CharityLogo>('CharityLogo');
}
