// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

export interface Charity {
  id: string;
  name: string;
  description: string;
  matchDonations: boolean;
  relationshipManager: string;
  logo: string;
  createdBy: string;
  readonly logoUploadedBefore2022: boolean;
  readonly logoLabel: string;
  readonly workdayMatched: boolean;
}

export interface CharityFiles {
  id: string;
  uploadedBy: string;
  uploadedDate: string;
  charity: string;
}

export interface CharityLogo {
  id: string;
  uploadedBy: string;
  uploadedDate: string;
}
