// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import { useQuery, useMutation } from '@workday/everywhere';
import type { QueryResult } from '@workday/everywhere';
import type { AttachedFile } from './models.js';

export function useAttachedFiles(options?: Parameters<typeof useQuery>[1]) {
  return useQuery<AttachedFile>('AttachedFile', options) as QueryResult<AttachedFile> & {
    data: AttachedFile[] | null;
  };
}

export function useAttachedFile(id: string) {
  return useQuery<AttachedFile>('AttachedFile', { id }) as QueryResult<AttachedFile> & {
    data: AttachedFile | null;
  };
}

export function useAttachedFileMutation() {
  return useMutation<AttachedFile>('AttachedFile');
}
