// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import type { CurrencyValue } from '@workday/everywhere';

export interface AttachedFile {
  id: string;
  uploadedBy: string;
  uploadedDate: string;
  event: string;
}

export interface EventImage {
  id: string;
  uploadedBy: string;
  uploadedDate: string;
}

export interface Registrant {
  id: string;
  worker: string;
  event: string;
}

export interface WorkEvent {
  id: string;
  name: string;
  location: string;
  description: string;
  sponsor: string;
  startDate: string;
  contactInfo: string;
  cost: CurrencyValue;
  createdBy: string;
  internalOnly: boolean;
  image: string;
  venue: string;
  registrants: Registrant[];
  endDate: string;
  readonly longDescription: string;
  readonly isWorkdayEvent: boolean;
  readonly proratedAmount: number;
  readonly imageUploadedDate: string;
  readonly requiresApprovalInternal: boolean;
  readonly requiresApproval: boolean;
}
