// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import { useQuery, useMutation } from '@workday/everywhere';
import type { Department } from './models.js';

export function useDepartments(options?: Parameters<typeof useQuery>[1]) {
  return useQuery<Department>('Department', options);
}

export function useDepartment(id: string) {
  return useQuery<Department>('Department', { id });
}

export function useDepartmentMutation() {
  return useMutation<Department>('Department');
}
