// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import { useQuery, useMutation } from '@workday/everywhere';
import type { Employee } from './models.js';

export function useEmployees(options?: Parameters<typeof useQuery>[1]) {
  return useQuery<Employee>('Employee', options);
}

export function useEmployee(id: string) {
  return useQuery<Employee>('Employee', { id });
}

export function useEmployeeMutation() {
  return useMutation<Employee>('Employee');
}
