// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

export interface Department {
  id: string;
  name: string;
  manager: string;
  headcount: string;
}

export interface Employee {
  id: string;
  name: string;
  email: string;
  department: string;
  title: string;
  startDate: string;
  photoUrl: string;
  isActive: boolean;
  isRemote: boolean;
  bio: string;
}
