// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import type { ModelSchema } from '@workday/everywhere';

export const schemas: Record<string, ModelSchema> = {
  Department: {
    name: 'Department',
    label: 'Department',
    collection: 'departments',
    fields: [
      { name: 'name', type: 'TEXT' },
      { name: 'manager', type: 'SINGLE_INSTANCE', target: 'Employee' },
      { name: 'headcount', type: 'TEXT' },
    ],
  },
  Employee: {
    name: 'Employee',
    label: 'Employee',
    collection: 'employees',
    fields: [
      { name: 'name', type: 'TEXT' },
      { name: 'email', type: 'TEXT' },
      { name: 'department', type: 'TEXT' },
      { name: 'title', type: 'TEXT' },
      { name: 'startDate', type: 'DATE', precision: 'DAY' },
      { name: 'photoUrl', type: 'TEXT' },
      { name: 'isActive', type: 'BOOLEAN' },
      { name: 'isRemote', type: 'BOOLEAN' },
      { name: 'bio', type: 'TEXT' },
    ],
  },
};
