// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import { useQuery, useMutation } from '@workday/everywhere';
import type { QueryResult } from '@workday/everywhere';
import type { EventImage } from './models.js';

export function useEventImages(options?: Parameters<typeof useQuery>[1]) {
  return useQuery<EventImage>('EventImage', options) as QueryResult<EventImage> & {
    data: EventImage[] | null;
  };
}

export function useEventImage(id: string) {
  return useQuery<EventImage>('EventImage', { id }) as QueryResult<EventImage> & {
    data: EventImage | null;
  };
}

export function useEventImageMutation() {
  return useMutation<EventImage>('EventImage');
}
