// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import { useQuery, useMutation } from '@workday/everywhere';
import type { QueryResult } from '@workday/everywhere';
import type { Registrant } from './models.js';

export function useRegistrants(options?: Parameters<typeof useQuery>[1]) {
  return useQuery<Registrant>('Registrant', options) as QueryResult<Registrant> & {
    data: Registrant[] | null;
  };
}

export function useRegistrant(id: string) {
  return useQuery<Registrant>('Registrant', { id }) as QueryResult<Registrant> & {
    data: Registrant | null;
  };
}

export function useRegistrantMutation() {
  return useMutation<Registrant>('Registrant');
}
