// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import type { ModelSchema } from '@workday/everywhere';

export const schemas: Record<string, ModelSchema> = {
  AttachedFile: {
    name: 'AttachedFile',
    label: 'Attached File',
    collection: 'attachedFiles',
    securityDomains: ['ManageCreateAnEvent'],
    fields: [
      { name: 'uploadedBy', type: 'SINGLE_INSTANCE', target: 'WORKER' },
      { name: 'uploadedDate', type: 'DATE', precision: 'DAY' },
      { name: 'event', type: 'SINGLE_INSTANCE', target: 'WorkEvent' },
    ],
  },
  EventImage: {
    name: 'EventImage',
    label: 'Event Image',
    collection: 'eventImages',
    securityDomains: ['ManageCreateAnEvent'],
    fields: [
      { name: 'uploadedBy', type: 'SINGLE_INSTANCE', target: 'WORKER' },
      { name: 'uploadedDate', type: 'DATE', precision: 'DAY' },
    ],
  },
  Registrant: {
    name: 'Registrant',
    label: 'Registrant',
    collection: 'registrants',
    securityDomains: ['RegisterForEvents', 'ManageCreateAnEvent'],
    fields: [
      { name: 'worker', type: 'SINGLE_INSTANCE', target: 'WORKER' },
      { name: 'event', type: 'SINGLE_INSTANCE', target: 'WorkEvent' },
    ],
  },
  WorkEvent: {
    name: 'WorkEvent',
    label: 'Work Event',
    collection: 'workEvents',
    securityDomains: ['RegisterForEvents', 'ManageCreateAnEvent'],
    fields: [
      { name: 'name', type: 'TEXT' },
      { name: 'location', type: 'TEXT' },
      { name: 'description', type: 'TEXT' },
      { name: 'sponsor', type: 'TEXT' },
      { name: 'startDate', type: 'DATE', precision: 'DAY' },
      { name: 'contactInfo', type: 'TEXT' },
      { name: 'cost', type: 'CURRENCY' },
      { name: 'createdBy', type: 'SINGLE_INSTANCE', target: 'WORKER' },
      { name: 'internalOnly', type: 'BOOLEAN' },
      { name: 'image', type: 'SINGLE_INSTANCE', target: 'EventImage' },
      { name: 'venue', type: 'SINGLE_INSTANCE', target: 'LOCATION' },
      { name: 'registrants', type: 'MULTI_INSTANCE', target: 'Registrant' },
      { name: 'endDate', type: 'DATE', precision: 'DAY' },
      { name: 'longDescription', type: 'TEXT', isDerived: true },
      { name: 'isWorkdayEvent', type: 'BOOLEAN', isDerived: true },
      { name: 'proratedAmount', type: 'DECIMAL', isDerived: true },
      { name: 'imageUploadedDate', type: 'DATE', isDerived: true, precision: 'DAY' },
      { name: 'requiresApprovalInternal', type: 'BOOLEAN', isDerived: true },
      { name: 'requiresApproval', type: 'BOOLEAN', isDerived: true },
    ],
  },
};
