// AUTO-GENERATED by `everywhere bind` -- do not edit manually.

import { useQuery, useMutation } from '@workday/everywhere';
import type { QueryResult } from '@workday/everywhere';
import type { WorkEvent } from './models.js';

type WorkEventMutationModel = Partial<WorkEvent> & Pick<WorkEvent, 'id'>;

export function useWorkEvents(options?: Parameters<typeof useQuery>[1]) {
  return useQuery<WorkEvent>('WorkEvent', options) as QueryResult<WorkEvent> & {
    data: WorkEvent[] | null;
  };
}

export function useWorkEvent(id: string) {
  return useQuery<WorkEvent>('WorkEvent', { id }) as QueryResult<WorkEvent> & {
    data: WorkEvent | null;
  };
}

export function useWorkEventMutation() {
  return useMutation<WorkEventMutationModel>('WorkEvent');
}
