export function renderTsConfig(): string {
  const config = {
    compilerOptions: {
      target: 'ES2020',
      lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      jsx: 'react-jsx',
      module: 'Preserve',
      moduleResolution: 'bundler',
      strict: true,
      noEmit: true,
      skipLibCheck: true,
    },
    include: ['**/*.ts', '**/*.tsx'],
    exclude: ['node_modules', 'dist'],
  };
  return JSON.stringify(config, null, 2) + '\n';
}

export function renderAgentsMd(): string {
  return `# Workday Everywhere Plugin — Agent Guide

This project is a **Workday Everywhere (WE) plugin** built with the \`@workday/everywhere\` SDK.

## Entry point

\`plugin.tsx\` must default-export a \`PluginDefinition\` created with \`plugin()\`:

\`\`\`typescript
import { plugin, route } from '@workday/everywhere';
export default plugin({ defaultRoute, routes, provider });
\`\`\`

## Routes and navigation

Define routes with \`route()\`. Add a type parameter to enable type-safe params:

\`\`\`typescript
const list = route('list', { component: ListPage });
const detail = route<{ id: string }>('detail', { component: DetailPage });
\`\`\`

Navigate between routes with \`useNavigate()\` and read params with \`useParams()\`:

\`\`\`typescript
import { useNavigate, useParams } from '@workday/everywhere';
const navigate = useNavigate();
navigate(detail, { id: '123' });
const { id } = useParams(detail);
\`\`\`

## Data layer

This plugin runs inside a **data provider** context. Data access goes through a \`DataResolver\`
wrapped in \`DataProvider\`. Pass the provider to \`plugin()\` so every page can access it:

\`\`\`typescript
import { DataProvider, GraphQLResolver } from '@workday/everywhere';
import { schema } from './everywhere/data/schema.js';

const resolver = new GraphQLResolver('your-app-referenceId', schema);

function Provider({ children }: { children: React.ReactNode }) {
  return <DataProvider resolver={resolver}>{children}</DataProvider>;
}

export default plugin({ defaultRoute, routes, provider: Provider });
\`\`\`

Data hooks are auto-generated by \`npx everywhere bind\` into \`everywhere/data/\` and follow this
pattern:

\`\`\`typescript
import { useEmployees } from './everywhere/data/Employee.js';
const { data, loading, error } = useEmployees();
\`\`\`

## Peer dependencies

\`react\` and \`react-dom\` (>=18) are **peer dependencies** — they are provided by the host
environment and must not be bundled with the plugin.

## Import conventions

All local imports must use \`.js\` extensions, even in \`.ts\`/\`.tsx\` source files:

\`\`\`typescript
import { helper } from './utils.js'; // correct
import { helper } from './utils';    // incorrect — omitting .js breaks ESM resolution
\`\`\`

## CLI reference

- \`npx everywhere dev\` — start the dev server with hot reload
- \`npx everywhere build\` — build the plugin bundle
- \`npx everywhere bind <bundle>\` — generate typed data hooks from a business object bundle
`;
}

export function renderStub(name: string): string {
  return `import { plugin, route } from '@workday/everywhere';

function HomePage() {
  return (
    <div style={{ padding: 16 }}>
      <h1>Welcome to ${name}!</h1>
      <p>This is a simple plugin with a single page.</p>
    </div>
  );
}

const home = route('home', { component: HomePage });

export default plugin({
  defaultRoute: home,
  routes: [home],
});
`;
}
