name: Publish package to npm
run-name: Publish ${{ github.ref_name }}

on:
  release:
    types: [released]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish package to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 'lts/*'

      - name: Clear auth token for OIDC
        run: echo "NODE_AUTH_TOKEN=" >> $GITHUB_ENV

      - name: Setup just
        uses: extractions/setup-just@v4

      - name: Install dependencies
        run: just setup

      - name: Build package
        run: just build

      - name: Publish to npm
        run: npm publish --provenance --access public
